### ISSUE TITLE
ci: cancel runs on new commits

### ISSUE THREAD

**Issue by YYYasin19** [Quantco/datajudge#142]
Our `CI` currently let's runners run on old commits even though a newer one arrived.
This can be solved pretty easy by adding the following concurrency group to the `ci.yaml` file:
```yaml
name: Workflow X

on: # ...

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs: # ...
```

This can save resources (and make this faster, if you have a limited amount of runners)
